<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_</name>
   <tag></tag>
   <elementGuidId>46cc9e93-3172-482d-b8f9-ab93b092ad12</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/main/div/div/div/div/div/span/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>50f53056-ced5-42ea-90d2-8ccda72eafef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/probation_client_nuxt/#/auth/register</value>
      <webElementGuid>920a5a9a-0981-43ee-9b25-2ffc984b9341</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>สมัครสมาชิก</value>
      <webElementGuid>c0e85ff9-b0a8-4006-8f8f-a558a0a62288</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;v-application--wrap&quot;]/main[@class=&quot;v-main bghhhP&quot;]/div[@class=&quot;v-main__wrap&quot;]/div[@class=&quot;w-full container mx-auto px-4 h-full flex flex-col justify-center items-center llbg pb-20&quot;]/div[@class=&quot;p-4 w-6/12&quot;]/div[@class=&quot;v-card v-sheet theme--light&quot;]/div[@class=&quot;v-card__text&quot;]/span[1]/a[1]</value>
      <webElementGuid>0c9aca8f-ac19-4f18-a101-c95c79649148</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div/div/span/a</value>
      <webElementGuid>c2dd2e5e-2e8d-4b04-9c5d-e571d96f6644</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'สมัครสมาชิก')]</value>
      <webElementGuid>880cab00-d25f-4900-93c2-908cccf832da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ยินดีต้อนรับ ผู้ประกอบการ'])[1]/following::a[1]</value>
      <webElementGuid>e8df56c5-6524-48a7-abf6-489d5afdac57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='​'])[1]/preceding::a[1]</value>
      <webElementGuid>6cf0d5bc-a9ea-42fe-a925-7111460503e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ชื่อผู้ใช้'])[1]/preceding::a[1]</value>
      <webElementGuid>ab20c790-f277-4e2a-beca-d53f465650ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='สมัครสมาชิก']/parent::*</value>
      <webElementGuid>69bd4997-57d5-478e-9b1d-f659835649da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/probation_client_nuxt/#/auth/register')]</value>
      <webElementGuid>d5b2c222-c9f7-450a-938b-313acc50a499</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a</value>
      <webElementGuid>ea3c9000-9996-4d3b-b13b-9ef0a6196a6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/probation_client_nuxt/#/auth/register' and (text() = 'สมัครสมาชิก' or . = 'สมัครสมาชิก')]</value>
      <webElementGuid>70b3e6cf-0b20-4f82-996a-ca319b186a26</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
